version: "3.9"
services:
  api:
    build: .
    ports:
      - "1338:80"
    volumes:
      - .:/usr/learnhouse
  frontend:
    build: ./front
    ports:
      - "3001:3000"
    volumes:
      - ./front:/usr/learnhouse/front
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=learnhouse
      - MONGO_INITDB_ROOT_PASSWORD=learnhouse
