version: "3.9"
services:
  api:
    build: apps/api/.
    ports:
      - "1338:80"
    volumes:
      - .:/usr/learnhouse
    environment:
      - LEARNHOUSE_COOKIE_DOMAIN=.localhost
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=learnhouse
      - POSTGRES_PASSWORD=learnhouse
      - POSTGRES_DB=learnhouse
  redis:
    image: redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=learnhouse
      - MONGO_INITDB_ROOT_PASSWORD=learnhouse
