name: Team
description: You are someone from the team
labels: ["team"]
body:
  - type: markdown
    attributes:
      value: |
        Issue Content
  - type: checkboxes
    id: planned
    label: Planned issue
    attributes:
      label: Is this issue planned ?
      options:
        - label: Planned
          
