site_name: LearnHouse
site_description: LearnHouse is an open-source platform tailored for learning experiences.
contact_email: hi@learnhouse.app

general:
  development_mode: true

security:
  auth_jwt_secret_key: secret

hosting_config:
  domain: learnhouse.app
  ssl: true
  allowed_origins:
    - http://localhost:3000
    - http://localhost:3001
  cookies_config:
    domain: ".localhost"
  allowed_regexp: '\b((?:https?://)[^\s/$.?#].[^\s]*)\b'

database_config:
  mongodb_connection_string: mongodb://learnhouse:learnhouse@mongo:27017/
