[tool.ruff]
# E501 line too long (82 > 79 characters)
ignore = ["E501", "E712"]

[tool.poetry]
name = "learnhouse-api"
version = "0.1.0"
description = "Learnhouse Backend"
authors = ["Badr B. (swve)"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.109.1"
pydantic = {version = ">=1.8.0,<2.0.0", extras = ["email"]}
sqlmodel = "0.0.10"
uvicorn = "0.23.2"
pymongo = "4.3.3"
motor = "3.1.1"
psycopg2 = "^2.9.9"
python-multipart = "^0.0.6"
boto3 = "^1.34.17"
botocore = "^1.34.17"
python-jose = "^3.3.0"
passlib = "^1.7.4"
fastapi-jwt-auth = "^0.5.0"
pytest = "^7.4.4"
httpx = "^0.26.0"
faker = "^22.2.0"
requests = "^2.31.0"
pyyaml = "^6.0.1"
sentry-sdk = {extras = ["fastapi"], version = "^1.39.2"}
langchain = "0.1.0"
tiktoken = "^0.5.2"
openai = "^1.7.1"
chromadb = "^0.4.22"
python-dotenv = "^1.0.0"
redis = "^5.0.1"
langchain-community = "^0.0.11"
langchain-openai = "^0.0.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
