name: App Build
on:
  push:
    paths:
      - "**"
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t learnhouse .
        working-directory: .
