name: Frontend Lint
on: [push, pull_request]
jobs:
  next-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: cd front && npm ci
      - name: Lint code
        run: cd front && npm run lint
