name: Web Lint
on:
  push:
    paths:
      - "apps/web/**"
  pull_request:
    paths:
      - "apps/web/**"
jobs:
  next-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
        working-directory: ./apps/web
      - name: Lint code
        run: npm run lint
        working-directory: ./apps/web
